# Generated by Django 3.1.5 on 2021-08-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=50)),
                ('cTitle', models.CharField(default='', max_length=100)),
                ('cForumAlias', models.CharField(default='', max_length=20)),
                ('cForumName', models.CharField(default='', max_length=20)),
                ('cCommentCount', models.IntegerField(default=0)),
                ('cLikeCount', models.IntegerField(default=0)),
                ('cContent', models.TextField(default='', max_length=800)),
                ('cTag', models.CharField(default='', max_length=100)),
                ('mood', models.CharField(default='', max_length=20)),
                ('link', models.URLField(default='')),
                ('img', models.URLField(default='https://i.imgur.com/Ewmac29.jpg')),
            ],
            options={
                'ordering': ['-cLikeCount'],
            },
        ),
    ]
