# Generated by Django 3.1.5 on 2021-07-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=50, unique=True)),
                ('cTitle', models.CharField(default='', max_length=100)),
                ('cForumAlias', models.CharField(default='', max_length=20)),
                ('cCommentCount', models.IntegerField(default=0)),
                ('cLikeCount', models.IntegerField(default=0)),
                ('cExcerpt', models.TextField(default='', max_length=100)),
                ('link', models.URLField(default='')),
                ('img', models.URLField(default='https://i.imgur.com/Ewmac29.jpg')),
            ],
        ),
    ]
