# Generated by Django 3.1.5 on 2021-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='cCommentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='cExcerpt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='cForumAlias',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='cLikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='cTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
