# Generated by Django 3.1.5 on 2021-07-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='num',
            field=models.CharField(default='', max_length=50),
        ),
    ]
