# Generated by Django 3.1.5 on 2021-07-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210715_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='cForumName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
