# Generated by Django 3.1.5 on 2021-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210714_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='CrawledData',
        ),
    ]
