# Generated by Django 3.1.5 on 2021-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210714_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='img',
            field=models.URLField(default='https://i.imgur.com/Ewmac29.jpg'),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='link',
            field=models.URLField(default=KeyError, verbose_name=models.CharField(default='', max_length=100)),
        ),
    ]
