# Generated by Django 3.1.5 on 2021-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_crawleddata_cforumname'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='cTag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
