# Generated by Django 3.1.5 on 2021-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210714_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='link',
            field=models.URLField(default=KeyError),
        ),
    ]
