# Generated by Django 3.1.5 on 2021-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210714_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='cExcerpt',
            field=models.TextField(default='', max_length=100),
        ),
    ]
