# Generated by Django 3.1.5 on 2021-07-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20210714_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='book',
        ),
        migrations.AddField(
            model_name='topic',
            name='cTitle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='tickets.crawleddata'),
        ),
    ]
