# Generated by Django 3.1.5 on 2021-07-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20210715_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='cTitle',
            new_name='CrawledData',
        ),
    ]
